services:
  webhook:
    container_name: webhook
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - APP_ID
      - APP_SECRET
      - WEBHOOK_SECRET
      - GENJIPK_WEBSITE_WEBHOOK_URL
      - GENJIPK_FRAMEWORK_WEBHOOK_URL
    networks:
      - caddy-network
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
networks:
  caddy-network:
    external: true