name: Main Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ init ]

jobs:
  deploy:
    uses: bkan0n/bkan0n-deploy-workflow/.github/workflows/main.yml@main
    secrets: inherit